version: "3.9"
services:
  scaffold-manager:
    image: "scaffold:test"
    ports:
      - "127.0.0.1:2997:2997"
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:19999:19999"
    environment:
      SCAFFOLD_KILL_SERVER_PORT: "19999"
      SCAFFOLD_RUN_MODE: "test"
      SCAFFOLD_SLEEP: "10"
      SCAFFOLD_HOST: "scaffold-manager"
      SCAFFOLD_WS_PORT: "8080"
      SCAFFOLD_LOG_LEVEL: "TRACE"
      SCAFFOLD_PROTOCOL: "https"
      SCAFFOLD_TLS_ENABLED: "true"
      SCAFFOLD_TLS_SKIP_VERIFY: "true"
      SCAFFOLD_TLS_CERT_CRT: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVRRENDQWlpZ0F3SUJBZ0lVS05nWVYwN2NoUmMrSVRsUzJDTnVRTkt4eExFd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1FERUxNQWtHQTFVRUJoTUNWVk14Q3pBSkJnTlZCQWdNQWtsTU1SRXdEd1lEVlFRS0RBaFRZMkZtWm05cwpaREVSTUE4R0ExVUVBd3dJYzJOaFptWnZiR1F3SGhjTk1qTXdPREUwTVRrME56SXlXaGNOTWpReE1qSTJNVGswCk56SXlXakJJTVFzd0NRWURWUVFHRXdKVlV6RUxNQWtHQTFVRUNBd0NTVXd4RVRBUEJnTlZCQW9NQ0ZOallXWm0KYjJ4a01Sa3dGd1lEVlFRRERCQnpZMkZtWm05c1pDMXRZVzVoWjJWeU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRgpBQU9DQVE4QU1JSUJDZ0tDQVFFQXV5MUFvT3FyNGlCMWxIb2tVYlF0ZlVaVzN3cFhCMmpacHZJa1B1MGh1M2tLCkRidG5LLzR0dEVYVk5wZDhYUXQ4RUxQVEp6bTZwTWdqWTFRM3R2Yy9XMEVuMFZCdXFmY2NLN0p2VmEzUEFSUkcKQ3V1ZjJTOEUwYnFHYkRmSGd1VWttbVR4eDBoMVE1NkZwakx2S2paWDNYTUxmYjdKaDRoeUhLTCtqelFidEpnVgpTWkVrWVlodDVLVXE3MGxJNTBGMU1lK0Z4bXVVMGhIdzUwbEN6cnlXbS9NSFRlVFE3RzJBdXZvdUJPUVV0bzZNCnVxT0xlekxRaVcyUXNORktocVJyeU1aL3dvTHR2NnIzbXkwUXpINUZwVzNIWjZYejE5ZlZWRXVodkdTREZTUHEKOEE0dUJzUk5DMWVhd050MFloUTU5ZU1ITng2azgzVjkreTNDQjBsMGN3SURBUUFCb3lvd0tEQW1CZ05WSFJFRQpIekFkZ2hCelkyRm1abTlzWkMxdFlXNWhaMlZ5Z2dsc2IyTmhiR2h2YzNRd0RRWUpLb1pJaHZjTkFRRUxCUUFECmdnSUJBSTkrOFpSODBxUDY0RjMzbE5ESkNIdG5JTWF6ZU56MDNIQVpBZFNQajdCMnZDMTluVEV4QUJnU0VKNDQKalViNzNiUE1QUCtKdnhsRy9NSW9YR3lzajMvQllFdnp3dCtFb1pTbW44SVR4K3NCWEVtK0lUQ1BBOFJSTE1CRQp6Vm82eFFOczhZdGdXeUR3UlFJYldDWlVSRVAva0pSRDhuT0VpTVN0eGJOemlmZmFqRmpDaHdUNXNpRGJBbkRvCitrTURYUHUzblR4U2Y5WHVqdlpmV0dhV2Jzd1JYYmdQUThoWUFtT0tSNG0yTnBFODhLYUNhb1BvdjFXOUo3dk0KV3ZWNXBLRFZ1d2NWM3lpS0QyblRBVGw0V1JlK3VQTlA1RW5JN3M1aVh2S2xIcU5kSmt0TTZyaTl4ZnNpZnYwNwpkaWYzK3hHSjF0em5UZmhOS0F2ZVpuWnRCRGlPTG1BTmgrQU5YV2N0TU9TaG5vSS9UR3EyWFJ6a0gyWU9oV1Q2CklqdmJpTjg4MjRnSDd5dXdpc0R3Y2x4UnZRMkdSMmk4YndJNmF6KzdQWUoxeGZZQ1F6S0hwenlKSVBtV3ZDU2sKeDQ0UTBhTVk3OVFneEpMZ2ZBMG12dUdKdThVeHAvck40OU05eEJNRkMxQ0sycVpEbkJ4Y1ZPZ1VLYnJqNlBJVwp3U0UrVjVYaFk1bStHekVrbmtVaUdTNGtpNGxPNFBKTVgxS2hickhhN3RaNUVpcGFNRDF1d25jZDB6YTJRWkZ4CmRLNUZMNEpaOC9zc0l6VjlBWFdGdE9TNCtURWwrUXFkOUxXVWZKQndlcFZoNG1mVHRVWTBsQm9xcFc1WFFNd24KUStkZEhaak11OUFCL0UxWXg4YXMxQjdCVWJhbFptcHp1RHUybG5reFJPT1pNa3BSCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K" # manager
      SCAFFOLD_TLS_CERT_KEY: "LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBdXkxQW9PcXI0aUIxbEhva1ViUXRmVVpXM3dwWEIyalpwdklrUHUwaHUza0tEYnRuCksvNHR0RVhWTnBkOFhRdDhFTFBUSnptNnBNZ2pZMVEzdHZjL1cwRW4wVkJ1cWZjY0s3SnZWYTNQQVJSR0N1dWYKMlM4RTBicUdiRGZIZ3VVa21tVHh4MGgxUTU2RnBqTHZLalpYM1hNTGZiN0poNGh5SEtMK2p6UWJ0SmdWU1pFawpZWWh0NUtVcTcwbEk1MEYxTWUrRnhtdVUwaEh3NTBsQ3pyeVdtL01IVGVUUTdHMkF1dm91Qk9RVXRvNk11cU9MCmV6TFFpVzJRc05GS2hxUnJ5TVovd29MdHY2cjNteTBRekg1RnBXM0haNlh6MTlmVlZFdWh2R1NERlNQcThBNHUKQnNSTkMxZWF3TnQwWWhRNTllTUhOeDZrODNWOSt5M0NCMGwwY3dJREFRQUJBb0lCQVFDVkdCK3h6aHZwL0djTQpSUnFuQmpseDMxU1ZSMXc1WjdodmRkT1BXRDRWWWYyeklJSzNGVGw4cmw5K283NEpNM3U0cGpUY3V1eEVFN08wCmpFSHcrUk03Y2pQd1UveENZTGJNeTg1SlZqQmNzTFIyUUdmTWpOcHU0UC93TmFJelRxa1FYcllFUW1BOTQ0aWIKOFZoMnJHRGk0Wi9Xb3VGT2wwNG1KMk5UMkhMMUx3NlNiejAwK0V4MDB3QmZybXFadWd0bTdySEVhcEhyelgvSApRTU1Zam5tU0U1K0l2SWJGNCtVVlcxNkdyYUU2cXNtUUFjOVc3a2FmdGRHL2U2V3dsNmFyamIraHRJempydEJDCk1qVlg4UFZKTURNSFNUc2MrZk1hZVlub1FUeGFrbjREWHZRKy8wVnpsZUpnZFN0YnVGSFlJUktNV1JSMjBWN2wKMUloNlhSalpBb0dCQU5zblNHV2RWZ3crazlJMHZCbm5tNmdqSHQ2d2NOMjFORWJFS0hVY1JtY0Z2bDR2alhWTwpiTUIwWHR6ZmR1d013SVEvR2kvVCtST0dGS0Y5d0xuUkMrOFpTK2pQUkUvVlBjUExNSHBlT0lEY0NoL3VSS0NoClB5cG5JRGhWT010c2tKOW1FUkxpZGR2M2Fvd3FsUi9JU3lwVEV1ckNBanUraUJvREhxRWFqYUVkQW9HQkFOcWwKcEU3cW5kdmRLVVJhdkEzU3BCK01DcGxaY2kybldKR3E5YU1yTEpBQlVrUi9kQm9zRTQ3TFBIcjdQZlE3NE5CbQo5bldDRGp6YjBjeWlsQVR0TGhoT1RPeGVtd0pKekxuMFh4NmtRMnNwWkNTK0l3N1A3Q01hNUFTMkthRll0ekJoCnQ3OG1NUit4WC9zWG1uemVFYi9TZ1F2d1g0YndsaisvWDFjNSs0YlBBb0dBR1ZnS3BFMjB0TWZMMm9Sa3VHNHoKYnhkWXE1SW1DMDI0VlBLOFp3YTFFWmIxYy9qMTEvb1EwNVRobjVOc01sSXJOV0FDekVNc1M5aTJyQkpaNW1OSgppUVlZNUR5TC90dC9RQlJRYitaVGpIdGw1Rmx1c0ZEVmVEYmk0QURqQjR0dmtpK0FpL21LZmJ5NElxdU9BVlh0CmMyQ1dFSFlOUWhGL3RkcGtnV2NMdC9VQ2dZQTM2bFJ5dWgxVXRPSncwS04zQlg5amNmVGo4clA0YU91RmxTcnMKWjRZbDdiQ1VRK1AxTFlCeTdCYXpmTDBEVUt6Vm52ODRYZUkyUGlFUkxDS2VmK2xoM2VSZUxuT0Z5a25JNUczTwo4RU10akpCSHRUaFIrV3B5TDlaUVBpVzNWWEREdHJtKzhJMXZoWFQrU2JNQWErb3VIQzlVVmt5WHZiOHUza29MCmpKQitrUUtCZ1FEWjZCOXh4bkpaWlhQc0JXZnZrQjAwMTJ0Z3Q0Q3JxcFZKUTk0VTVycndneVdwTUlhdC9zQWYKSEQ1MW9XNU5vR2Z6bCsvN2pGSmJZU0diZXZpL3RlbFprQUhsZFh3ako5WGptZnd0eFdHQmwraTlQem1sbG9wUAo5NExnVk9DdXhEcTVWTy8rc3dCblFGMmp1WG4xZWhwSGpsTXkvaW9YVDM4M2xrOFRhd3Z0dHc9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=" # manager
      SCAFFOLD_LOG_FORMAT: "json"
      SCAFFOLD_DB: |
        {
          "username": "MyCoolMongoDBUsername",
          "password": "MyCoolMongoDBPassword",
          "name": "scaffold",
          "host": "mongodb",
          "port": 27017,
          "protocol": "http"
        }
      SCAFFOLD_NODE: |
        {
          "type": "manager",
          "manager_host": "scaffold-manager",
          "manager_port": 2997,
          "manager_protocol": "https",
          "join_key": "MyCoolJoinKey12345",
          "primary_key": "MyCoolPrimaryKey12345"
        }
      SCAFFOLD_FILE_STORE: |
        {
          "access_key": "MyCoolMinIOAccessKey",
          "secret_key": "MyCoolMinIOSecretKey",
          "host": "minio",
          "port": 9090,
          "bucket": "scaffold",
          "region": "default-region",
          "protocol": "http"
        }
    depends_on:
      - "mongodb"
      - "minio"
    tty: true
  scaffold-worker:
    image: "scaffold:test"
    ports:
      - "127.0.0.1:2998:2998"
      - "127.0.0.1:8081:8081"
      - "127.0.0.1:29999:29999"
    environment:
      SCAFFOLD_KILL_SERVER_PORT: "29999"
      SCAFFOLD_RUN_MODE: "test"
      SCAFFOLD_PORT: "2998"
      SCAFFOLD_HOST: "scaffold-worker"
      SCAFFOLD_LOG_LEVEL: "TRACE"
      SCAFFOLD_WS_PORT: "8081"
      SCAFFOLD_SLEEP: "20"
      SCAFFOLD_PROTOCOL: "https"
      SCAFFOLD_TLS_ENABLED: "true"
      SCAFFOLD_TLS_SKIP_VERIFY: "true"
      SCAFFOLD_TLS_CERT_CRT: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVQakNDQWlhZ0F3SUJBZ0lVS05nWVYwN2NoUmMrSVRsUzJDTnVRTkt4eExJd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1FERUxNQWtHQTFVRUJoTUNWVk14Q3pBSkJnTlZCQWdNQWtsTU1SRXdEd1lEVlFRS0RBaFRZMkZtWm05cwpaREVSTUE4R0ExVUVBd3dJYzJOaFptWnZiR1F3SGhjTk1qTXdPREUwTVRrME56SXlXaGNOTWpReE1qSTJNVGswCk56SXlXakJITVFzd0NRWURWUVFHRXdKVlV6RUxNQWtHQTFVRUNBd0NTVXd4RVRBUEJnTlZCQW9NQ0ZOallXWm0KYjJ4a01SZ3dGZ1lEVlFRRERBOXpZMkZtWm05c1pDMTNiM0pyWlhJd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQQpBNElCRHdBd2dnRUtBb0lCQVFDelNXb3h6V3lyVGltMU1IWEZTZzd0d1NHYmNpRk1tRHFlYy94V1Fjd21XQjV0Cm1mbkl0UEx3amZIWWx2OXBVSDFGUlgvUG5wU3VhNTBaOHBKZ0hXcVFxb3B0c1hPblZld0Q3TzZkQzdJT2VWaTgKdzlsWXdjTUNvQlpERENwZzZTcHRPUEZzY1FHanBPbEM4ajNnQi9YL0lESGoxMjJHMm5rbzh6em9GS0Fzd2hMKwpTNFNVQS9saGJNSVF4WVZ6ZVZ4aUt1U1pzUXAyRDVLZ0lMbWN0UXE3cGhJZ3JVOXZ1ajhTc25SSXFYL2VWRElOCm9YNm5uY3lzeWFwbGtYUFVqQkNyUGszUFdGbVBKakQ4LzM2TzNEQURYZTlPQWE0RFNaWUFSd0ZKUk4xVzE1ZDgKK1dORHFxSU1DZ0tJRWtoTDZDMERkaHgydUZFRm15QzVOb0NSMGpYVEFnTUJBQUdqS1RBbk1DVUdBMVVkRVFRZQpNQnlDRDNOallXWm1iMnhrTFhkdmNtdGxjb0lKYkc5allXeG9iM04wTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElDCkFRQk53R1pKL1J5UUs2cDhFODZiMWxqVmY0OVliWDN5bXRNZWRBdHlHc0tZb2lRNkRnRHE2NDBBM2RjZ3pCT3kKMnliWDhhWlJLdkRJem92OEpiekwvazFLZzBrK2REMzJEaHM5cHBwT2RmNU50VzAzZ0lSeVBnS2xUUjVrMVRhVwpoN1VuM3FFNFkybGt4OXhQMFh0ZlRwYkFsU3VkV2xacnA4aW1uekFyN1Y5S2x6L2t3MkVaTmFiQ2RncXZROVlMCkZreXkvcjFiWnVSbldrWE5SQkRoVXpENnpjUHMvR1ltaHpETTJac3VBa2F4S2NheGUydzM1Qy9COTRkenl1SUIKVU9JRGlycURlcERzZDRZY0JGY1J2TVZwS0N2YWR2bVJtZ1Y2aGFRdk1NMlkwVjNnQWJlakMvczdzemlLK1VoYQpQeGpoMSttSzJ6OWQ5d2FxaUoxWkdkMmpWdEFzWHZFSVRQb3FQZkNHTnBqNGxjQzFEZFFNcGpSWnl4aDRiZlk3Ck5ZbE9MQ0ZhaG5XK3hKL3JtWmUrQTN6ZmVKcU9nMGhicWF0djE2eFkxK1daS1dkRERDUTROalovd1lSSHZuTWYKM3RNaVg2Vy9YT2hUUlJGWndrUUhSMU1iY29zRXdsdFdWcE5kVkx6aXlVN2hnUlhITDRCYmlPc1lTajJWZWdRLwo4N09MbG5DSjhYemU1TFFQcmJHdkRyY0FsNHhqRXZTUmVHQUdUV2c2TUJXQUpDU25FYlFkSldPWVV4QkpEVEYrCjFscWRwQjQ4V2xEdkwreW1VaElCZ0dlNnU1L1VnT2cvV1JEcW8zTDVJczc5ZWs3K0d1ZUJOa1k0OGsvMEVzUVUKdUxzVkxvWjJLcWVTRWdPemJvZHJma0pnMVF1aHNYSXNaVWxvem90elFiditEQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K" # worker
      SCAFFOLD_TLS_CERT_KEY: "LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBczBscU1jMXNxMDRwdFRCMXhVb083Y0VobTNJaFRKZzZublA4VmtITUpsZ2ViWm41CnlMVHk4STN4MkpiL2FWQjlSVVYvejU2VXJtdWRHZktTWUIxcWtLcUtiYkZ6cDFYc0ErenVuUXV5RG5sWXZNUFoKV01IREFxQVdRd3dxWU9rcWJUanhiSEVCbzZUcFF2STk0QWYxL3lBeDQ5ZHRodHA1S1BNODZCU2dMTUlTL2t1RQpsQVA1WVd6Q0VNV0ZjM2xjWWlya21iRUtkZytTb0NDNW5MVUt1NllTSUsxUGI3by9FckowU0tsLzNsUXlEYUYrCnA1M01yTW1xWlpGejFJd1FxejVOejFoWmp5WXcvUDkranR3d0ExM3ZUZ0d1QTBtV0FFY0JTVVRkVnRlWGZQbGoKUTZxaURBb0NpQkpJUytndEEzWWNkcmhSQlpzZ3VUYUFrZEkxMHdJREFRQUJBb0lCQURqRjZiUGxtaURRK3BJZQp5MXh6TERFTHRHbTJCV2RzMlRzdC9WMFBMdWVCaGZrdEJoVVJmOUMvRWpPRTlWSlRJNmdZN3ZVL0FWUU9UY3hXCnJSVjBtemMrV2VHTWpOUVRlRTV4NjhtZFY0QVAyeExEYmdNV01IdVhXQlZaTjk1Q1Y2WUlueUs0MGswUXZyRHQKWnJ5WHFNVm1XNFlMeE9vc0txdldBcFozV1pWeVF4VndyZDRKNkw3MWJQcVFPNnpLMkd6MVZYNmxzUU1OSWRPVApsZDd2bmJzK0VmdVhwR2dUN21VdmlTOE5hSnVaRVcrWU5yelEzQlUxeHczaG40a0crU0xKZzhKNEYrbkY5NmhiCmEwVElBRGpsVCtEVGdtVjZBaDdnano2bHh3Ym1Ib1g0Rk91aURKcWVKNHFNeWVlS09SU2pTVS9sRFQ5NGVXajEKYjV3aCtiRUNnWUVBN055NnliZWtPRno3ZU5ybG1nZmdFdVRSc2M0cmtMRFJ6ajNhQjZZYk03SkFreU5aTkhWRgpRcXpWbjgxRk0yQTJseXdxOWdQM2Vqc2xBNm9UNnNpSGVvS0Zxb2hMenp3M2Ric0xLR202NFRvVSsxWXQxUXI5Cm1mZU1VVi9taTQ3Mzh4MUFPVlowZjBVa0NFeUsramd3ZmtoVnNIQUszUUtEZGNVQWhzM202L2tDZ1lFQXdjWEsKcXBHc01CTjZPdU9VM2ZsbTZ4TmRQU2c0aXY1OUpoWE5pc1JLWGJTd3lpRXhVYkNtTEtEbXg3NlRpUzc4cXlyMgpiK2YwNmNhWmxVSFErdlUzTERZN3BhaVRabjJqeG5kM0ZmWHJKNUtodjBmNnNJSnB4SDBMbFJFZEJOd3phRjlsCkpja09hWk1xZkx2d0RaSCt3SjZIUFZKSEdteTgxNjFvRm9tRDZ5c0NnWUFTZERnUlV6OTJMTGhpK0JyL1h6RzAKQnlQWFNJcllZUTVYbFRZUmRuMlVENFU4Y1hxWHZiTkJ1Sm1FTThmNmNycU9HS0RZUGdMZ0FRK25NMjhOMGNYTQpZN0xxVUdnbm96ZG04c1d4eGxzTEJTMXhUNHVPbDZhZWdrenFZaUJpS3lkaVI1c2pYSHNERjIzeFA1VnNYVWhaCjdtVE90RXdFWUJmQjZ6RlpUMTE0Y1FLQmdHVmFObXBITGFBcjMrZ0RkNjh2TDFUUDJSb08rcHhCQm1hd1NzVkYKYkh4YzhZZVlHdnJXZ2VTZitIWUx5Wkdjb1E1S3Q0SEsrc0I0WDRiQldUU2FwRlFjdmRBbFA0d0JOWE91c3Z3cQpsK2duK3pCWXp0Z2FMb1pXdllNbjQxelNiSlV3S0hDK0hDcStqaCtXRWJhWFlYK1FxNzQ0VmZhTlg2MFVCM2lhClR3VG5Bb0dCQU95STlGUGhSazQzM1cvNURReHJ6NzZwWjArRnVRYU1PNjN6ODEvYTQrdzA4SlBIUkFZUVpjQ2cKbWZPMWt4bzJhL0F2ZDI1YkhCY1M1NUZDdE13Y3pOZjNDV2w5V2pjMWcyNVJKeXpObWptTzBJaHpZbHNXay9zWAo5R05mVXFlYnBQbmpSM0kvZWhWTDgrVXU0UkFaakhjY01hakU5c0tCVDJhSmVRR0FjT0VvCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==" # worker
      SCAFFOLD_LOG_FORMAT: "json"
      SCAFFOLD_DB: |
        {
          "username": "MyCoolMongoDBUsername",
          "password": "MyCoolMongoDBPassword",
          "name": "scaffold",
          "host": "mongodb",
          "port": 27017,
          "protocol": "http"
        }
      SCAFFOLD_NODE: |
        {
          "type": "worker",
          "manager_host": "scaffold-manager",
          "manager_port": 2997,
          "manager_protocol": "https",
          "join_key": "MyCoolJoinKey12345",
          "primary_key": "MyCoolPrimaryKey12345"
        }
      SCAFFOLD_FILE_STORE: |
        {
          "access_key": "MyCoolMinIOAccessKey",
          "secret_key": "MyCoolMinIOSecretKey",
          "host": "minio",
          "port": 9090,
          "bucket": "scaffold",
          "region": "default-region",
          "protocol": "http"
        }
    depends_on:
      - "scaffold-manager"
    security_opt:
      - seccomp:unconfined
    privileged: true
    tty: true
  mongodb:
    image: centos/mongodb-36-centos7:1
    ports:
      - "127.0.0.1:27017:27017"
    environment:
      MONGODB_DATABASE: scaffold
      MONGODB_ADMIN_PASSWORD: MyCoolAdminPassword
      MONGODB_USER: MyCoolMongoDBUsername
      MONGODB_PASSWORD: MyCoolMongoDBPassword
  minio:
    image: bitnami/minio:2023
    ports:
      - "127.0.0.1:9090:9090"
      - "127.0.0.1:9091:9091"
    environment:
      BITNAMI_DEBUG: "false"
      MINIO_REGION: "default-region"
      MINIO_ROOT_USER: MyCoolMinIOAccessKey
      MINIO_ROOT_PASSWORD: MyCoolMinIOSecretKey
      MINIO_CONSOLE_PORT_NUMBER: "9091"
      MINIO_SERVER_PORT_NUMBER: "9090"
      MINIO_API_PORT_NUMBER: "9090"
